[colors]
background = '#0904048e'
black = '#090404'
blue = '#575757'
cursor = '#c1c0c0'
cyan = '#686868'
foreground = '#c1c0c0'
green = '#787878'
magenta = '#888888'
red = '#979797'
tabs = '#c1c0c0'
tabs-active = '#A7A7A7'
white = '#c1c0c0'
yellow = '#c1c0c0'
dim-black = '#0904048e'
dim-blue = '#5757578e'
dim-cyan = '#6868688e'
dim-foreground = '#c1c0c08e'
dim-green = '#7878788e'
dim-magenta = '#8888888e'
dim-red = '#9797978e'
dim-white = '#A7A7A78e'
dim-yellow = '#c1c0c08e'
light-black = '#575757'
light-blue = '#686868'
light-cyan = '#787878'
light-foreground = '#888888'
light-green = '#979797'
light-magenta = '#A7A7A7'
light-red = '#c1c0c0'
light-white = '#575757'
light-yellow = '#686868'
