[colors.primary]
background = "#090404"
foreground = "#c1c0c0"

[colors.cursor]
text = "#090404"
cursor = "#c1c0c0"

[colors.vi_mode_cursor]
text = "#090404"
cursor = "#c1c0c0"

[colors.search.matches]
foreground = "#090404"
background = "#c1c0c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#665353"
background = "#c1c0c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#090404"
red = "#575757"
green = "#686868"
yellow = "#787878"
blue = "#888888"
magenta = "#979797"
cyan = "#A7A7A7"
white = "#c1c0c0"

[colors.bright]
black = "#665353"
red = "#575757"
green = "#686868"
yellow = "#787878"
blue = "#888888"
magenta = "#979797"
cyan = "#A7A7A7"
white = "#c1c0c0"

[colors.dim]
black = "#c1c0c0"
red = "#575757"
green = "#979797"
yellow = "#787878"
blue = "#888888"
magenta = "#686868"
cyan = "#A7A7A7"
white = "#665353"

