[colors.primary]
background = "#080b14"
foreground = "#c1c2c4"

[colors.cursor]
text = "#080b14"
cursor = "#c1c2c4"

[colors.vi_mode_cursor]
text = "#080b14"
cursor = "#c1c2c4"

[colors.search.matches]
foreground = "#080b14"
background = "#c1c2c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#585d6b"
background = "#c1c2c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#080b14"
red = "#1A4C5E"
green = "#124676"
yellow = "#083B86"
blue = "#15518B"
magenta = "#276CA2"
cyan = "#3585B8"
white = "#c1c2c4"

[colors.bright]
black = "#585d6b"
red = "#1A4C5E"
green = "#124676"
yellow = "#083B86"
blue = "#15518B"
magenta = "#276CA2"
cyan = "#3585B8"
white = "#c1c2c4"

[colors.dim]
black = "#c1c2c4"
red = "#1A4C5E"
green = "#276CA2"
yellow = "#083B86"
blue = "#15518B"
magenta = "#124676"
cyan = "#3585B8"
white = "#585d6b"

