[colors]
background = '#080b148e'
black = '#080b14'
blue = '#1A4C5E'
cursor = '#c1c2c4'
cyan = '#124676'
foreground = '#c1c2c4'
green = '#083B86'
magenta = '#15518B'
red = '#276CA2'
tabs = '#c1c2c4'
tabs-active = '#3585B8'
white = '#c1c2c4'
yellow = '#c1c2c4'
dim-black = '#080b148e'
dim-blue = '#1A4C5E8e'
dim-cyan = '#1246768e'
dim-foreground = '#c1c2c48e'
dim-green = '#083B868e'
dim-magenta = '#15518B8e'
dim-red = '#276CA28e'
dim-white = '#3585B88e'
dim-yellow = '#c1c2c48e'
light-black = '#1A4C5E'
light-blue = '#124676'
light-cyan = '#083B86'
light-foreground = '#15518B'
light-green = '#276CA2'
light-magenta = '#3585B8'
light-red = '#c1c2c4'
light-white = '#1A4C5E'
light-yellow = '#124676'
